export const notificationData = [
  {
    id: 1,
    name: "John Doe",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    time: "2 hours ago",
  },
  {
    id: 2,
    name: "On Doe",
    message: "Lorem ipsum dolor sit amet, consectetur ",
    time: "2 min ago",
  },
  {
    id: 3,
    name: "Jane Doe",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    time: "2 hours ago",
  },
  {
    id: 4,
    name: "Jane Doe",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    time: "2 hours ago",
  },
];

export const accoundData = {
  name: "John",
  surname: "Doe",
  fatherName: "Doe",
  email: "johndoe@gmail.com",
  phone: "+1234567890",
  address: "1234 North Street, New York",
  image: null,
  joinDate: "12-12-2021",
  point: 537,
  university: "Harvard University",
  faculty: "Computer Science",
};


export const studentPaymentData = [
  {
    id: 1,
    paymentDate: "12-01-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Alice Johnson",
  },
  {
    id: 2,
    paymentDate: "12-02-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Bob Smith",
  },
  {
    id: 3,
    paymentDate: "12-03-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Charlie Brown",
  },
  {
    id: 4,
    paymentDate: "12-04-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Diana Prince",
  },
  {
    id: 5,
    paymentDate: "12-05-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Edward Norton",
  },
  {
    id: 6,
    paymentDate: "12-06-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Fiona Gallagher",
  },
  {
    id: 7,
    paymentDate: "12-07-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "George Michael",
  },
  {
    id: 8,
    paymentDate: "12-08-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Helen Hunt",
  },
  {
    id: 9,
    paymentDate: "12-09-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Isaac Newton",
  },
  {
    id: 10,
    paymentDate: "12-10-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Jessica Alba",
  },
  {
    id: 11,
    paymentDate: "12-11-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Kevin Spacey",
  },
  {
    id: 12,
    paymentDate: "12-12-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Laura Palmer",
  },
  {
    id: 13,
    paymentDate: "12-01-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Michael Jordan",
  },
  {
    id: 14,
    paymentDate: "12-02-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Nancy Drew",
  },
  {
    id: 15,
    paymentDate: "12-03-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Oliver Twist",
  },
  {
    id: 16,
    paymentDate: "12-04-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Pam Beesly",
  },
  {
    id: 17,
    paymentDate: "12-05-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Quentin Tarantino",
  },
  {
    id: 18,
    paymentDate: "12-06-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Rachel Green",
  },
  {
    id: 19,
    paymentDate: "12-07-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Sam Winchester",
  },
  {
    id: 20,
    paymentDate: "12-08-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Tony Stark",
  },
  {
    id: 21,
    paymentDate: "12-09-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Uma Thurman",
  },
  {
    id: 22,
    paymentDate: "12-10-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Victor Frankenstein",
  },
  {
    id: 23,
    paymentDate: "12-11-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Walter White",
  },
  {
    id: 24,
    paymentDate: "12-12-2022",
    paymentAmount: 120,
    isPaid: false,
    receiverName: "Xena Warrior",
  },
];

