import { id } from "date-fns/locale";
import { date } from "yup";

export const notificationData = [
  {
    id: 1,
    name: "John Doe",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    time: "2 hours ago",
  },
  {
    id: 2,
    name: "On Doe",
    message: "Lorem ipsum dolor sit amet, consectetur ",
    time: "2 min ago",
  },
  {
    id: 3,
    name: "Jane Doe",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    time: "2 hours ago",
  },
  {
    id: 4,
    name: "Jane Doe",
    message: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    time: "2 hours ago",
  },
];

export const accoundData = {
  id: 1,
  name: "John",
  surname: "Doe",
  fatherName: "Doe",
  email: "johndoe@gmail.com",
  phone: "+1234567890",
  address: "1234 North Street, New York",
  image: null,
  joinDate: "12-12-2021",
  point: 537,
  university: "Harvard University",
  faculty: "Computer Science",
};

export const studentPaymentData = [
  {
    id: 1,
    paymentDate: "12-01-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Alice Johnson",
  },
  {
    id: 2,
    paymentDate: "12-02-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Bob Smith",
  },
  {
    id: 3,
    paymentDate: "12-03-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Charlie Brown",
  },
  {
    id: 4,
    paymentDate: "12-04-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Diana Prince",
  },
  {
    id: 5,
    paymentDate: "12-05-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Edward Norton",
  },
  {
    id: 6,
    paymentDate: "12-06-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Fiona Gallagher",
  },
  {
    id: 7,
    paymentDate: "12-07-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "George Michael",
  },
  {
    id: 8,
    paymentDate: "12-08-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Helen Hunt",
  },
  {
    id: 9,
    paymentDate: "12-09-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Isaac Newton",
  },
  {
    id: 10,
    paymentDate: "12-10-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Jessica Alba",
  },
  {
    id: 11,
    paymentDate: "12-11-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Kevin Spacey",
  },
  {
    id: 12,
    paymentDate: "12-12-2021",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Laura Palmer",
  },
  {
    id: 13,
    paymentDate: "12-01-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Michael Jordan",
  },
  {
    id: 14,
    paymentDate: "12-02-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Nancy Drew",
  },
  {
    id: 15,
    paymentDate: "12-03-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Oliver Twist",
  },
  {
    id: 16,
    paymentDate: "12-04-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Pam Beesly",
  },
  {
    id: 17,
    paymentDate: "12-05-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Quentin Tarantino",
  },
  {
    id: 18,
    paymentDate: "12-06-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Rachel Green",
  },
  {
    id: 19,
    paymentDate: "12-07-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Sam Winchester",
  },
  {
    id: 20,
    paymentDate: "12-08-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Tony Stark",
  },
  {
    id: 21,
    paymentDate: "12-09-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Uma Thurman",
  },
  {
    id: 22,
    paymentDate: "12-10-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Victor Frankenstein",
  },
  {
    id: 23,
    paymentDate: "12-11-2022",
    paymentAmount: 120,
    isPaid: true,
    receiverName: "Walter White",
  },
  {
    id: 24,
    paymentDate: "12-12-2022",
    paymentAmount: 120,
    isPaid: false,
    receiverName: "Xena Warrior",
  },
];

export const studentCourseData = [
  {
    id: 1,
    name: "Riyaziyyat",
    teacher: null,
    days: "2-4-6",
    time: "10:00 - 12:00",
  },
  {
    id: 2,
    name: "İngilis dili",
    teacher: "Jane Smith",
    days: "1-3-5",
    time: "09:00 - 11:00",
  },
  {
    id: 3,
    name: "Məntiq",
    teacher: "Robert Brown",
    days: "2-4",
    time: "11:00 - 13:00",
  },
  {
    id: 4,
    name: "Azərbaycan dili",
    teacher: "Leyla Aliyeva",
    days: "1-3-5",
    time: "12:00 - 14:00",
  },
  {
    name: "Fizika",
    teacher: "Michael Johnson",
    days: "2-4-6",
    time: "13:00 - 15:00",
  },
  {
    name: "Kimya",
    teacher: "Anna White",
    days: "1-3-5",
    time: "14:00 - 16:00",
  },
];

export const absences = [
  {
    id: 1,
    studentId: 1,
    subjectId: 1,
    date: "2023-11-01",
    absence: true,
  },
  {
    id: 2,
    date: "2023-11-02",
    absence: false,
  },
  {
    id: 3,
    date: "2023-11-03",
    absence: true,
  },
  {
    id: 4,
    date: "2024-11-04",
    absence: false,
  },
  {
    id: 5,
    date: "2023-11-05",
    absence: true,
  },
  {
    id: 6,
    date: "2023-11-06",
    absence: false,
  },
  {
    id: 7,
    date: "2023-11-07",
    absence: true,
  },
  {
    id: 8,
    date: "2023-11-08",
    absence: false,
  },
  {
    id: 9,
    date: "2023-11-09",
    absence: true,
  },
  {
    id: 10,
    date: "2023-11-10",
    absence: false,
  },
  {
    id: 11,
    date: "2023-11-11",
    absence: true,
  },
  {
    id: 12,
    date: "2023-11-12",
    absence: false,
  },
  {
    id: 13,
    date: "2023-11-13",
    absence: true,
  },
  {
    id: 14,
    date: "2023-11-14",
    absence: false,
  },
  {
    id: 15,
    date: "2023-11-15",
    absence: true,
  },
  {
    id: 16,
    date: "2023-11-16",
    absence: false,
  },
  {
    id: 17,
    date: "2023-11-17",
    absence: true,
  },
  {
    id: 18,
    date: "2023-11-18",
    absence: false,
  },
  {
    id: 19,
    date: "2023-11-19",
    absence: true,
  },
  {
    id: 20,
    date: "2023-11-20",
    absence: false,
  },
  {
    id: 21,
    date: "2023-11-21",
    absence: true,
  },
  {
    id: 22,
    date: "2023-11-22",
    absence: false,
  },
];

export const coursesStudents = [
  {
    id: 11,
    name: "Ali",
    surname: "Yılmaz",
    absences: [
      { date: "2024-10-20", absence: true },
      { date: "2024-10-21", absence: false },
      { date: "2024-10-22", absence: true },
      { date: "2024-10-23", absence: false },
      { date: "2024-10-24", absence: true },
      { date: "2024-10-25", absence: false },
      { date: "2024-10-26", absence: true },
      { date: "2024-10-27", absence: false },
      { date: "2024-10-28", absence: true },
      { date: "2024-10-29", absence: false },
      { date: "2024-10-30", absence: true },
      { date: "2024-10-31", absence: false },
      { date: "2024-11-01", absence: true },
      { date: "2024-11-02", absence: null },
      { date: "2024-11-03", absence: null },
      { date: "2024-11-04", absence: null },
      { date: "2024-11-05", absence: null },
      { date: "2024-11-06", absence: null },
      { date: "2024-11-07", absence: null },
      { date: "2024-11-08", absence: null },
      { date: "2024-11-09", absence: null },
      { date: "2024-11-10", absence: null },
    ],
  },
  {
    id: 21,
    name: "Ayşe",
    surname: "Demir",
    absences: [
      { date: "2024-10-20", absence: false },
      { date: "2024-10-21", absence: true },
      { date: "2024-10-22", absence: false },
      { date: "2024-10-23", absence: true },
      { date: "2024-10-24", absence: false },
      { date: "2024-10-25", absence: true },
      { date: "2024-10-26", absence: false },
      { date: "2024-10-27", absence: true },
      { date: "2024-10-28", absence: false },
      { date: "2024-10-29", absence: true },
      { date: "2024-10-30", absence: false },
      { date: "2024-10-31", absence: true },
      { date: "2024-11-01", absence: false },
      { date: "2024-11-02", absence: null },
      { date: "2024-11-03", absence: null },
      { date: "2024-11-04", absence: null },
      { date: "2024-11-05", absence: null },
      { date: "2024-11-06", absence: null },
      { date: "2024-11-07", absence: null },
      { date: "2024-11-08", absence: null },
      { date: "2024-11-09", absence: null },
      { date: "2024-11-10", absence: null },
    ],
  },
  {
    id: 31,
    name: "Ali",
    surname: "Huseynov",
    absences: [
      { date: "2024-10-20", absence: false },
      { date: "2024-10-21", absence: true },
      { date: "2024-10-22", absence: false },
      { date: "2024-10-23", absence: true },
      { date: "2024-10-24", absence: false },
      { date: "2024-10-25", absence: true },
      { date: "2024-10-26", absence: false },
      { date: "2024-10-27", absence: true },
      { date: "2024-10-28", absence: false },
      { date: "2024-10-29", absence: true },
      { date: "2024-10-30", absence: false },
      { date: "2024-10-31", absence: true },
      { date: "2024-11-01", absence: false },
      { date: "2024-11-02", absence: null },
      { date: "2024-11-03", absence: null },
      { date: "2024-11-04", absence: null },
      { date: "2024-11-05", absence: null },
      { date: "2024-11-06", absence: null },
      { date: "2024-11-07", absence: null },
      { date: "2024-11-08", absence: null },
      { date: "2024-11-09", absence: null },
      { date: "2024-11-10", absence: null },
    ],
  },
  {
    id: 41,
    name: "Elvin",
    surname: "Memmedov",
    absences: [
      { date: "2024-10-20", absence: false },
      { date: "2024-10-21", absence: true },
      { date: "2024-10-22", absence: false },
      { date: "2024-10-23", absence: true },
      { date: "2024-10-24", absence: false },
      { date: "2024-10-25", absence: true },
      { date: "2024-10-26", absence: false },
      { date: "2024-10-27", absence: true },
      { date: "2024-10-28", absence: false },
      { date: "2024-10-29", absence: true },
      { date: "2024-10-30", absence: false },
      { date: "2024-10-31", absence: true },
      { date: "2024-11-01", absence: false },
      { date: "2024-11-02", absence: null },
      { date: "2024-11-03", absence: null },
      { date: "2024-11-04", absence: null },
      { date: "2024-11-05", absence: null },
      { date: "2024-11-06", absence: null },
      { date: "2024-11-07", absence: null },
      { date: "2024-11-08", absence: null },
      { date: "2024-11-09", absence: null },
      { date: "2024-11-10", absence: null },
    ],
  },
  {
    id: 51,
    name: "Namiq",
    surname: "Memmedov",
    absences: [
      { date: "2024-10-20", absence: false },
      { date: "2024-10-21", absence: true },
      { date: "2024-10-22", absence: false },
      { date: "2024-10-23", absence: true },
      { date: "2024-10-24", absence: false },
      { date: "2024-10-25", absence: true },
      { date: "2024-10-26", absence: false },
      { date: "2024-10-27", absence: true },
      { date: "2024-10-28", absence: false },
      { date: "2024-10-29", absence: true },
      { date: "2024-10-30", absence: false },
      { date: "2024-10-31", absence: true },
      { date: "2024-11-01", absence: false },
      { date: "2024-11-02", absence: null },
      { date: "2024-11-03", absence: null },
      { date: "2024-11-04", absence: null },
      { date: "2024-11-05", absence: null },
      { date: "2024-11-06", absence: null },
      { date: "2024-11-07", absence: null },
      { date: "2024-11-08", absence: null },
      { date: "2024-11-09", absence: null },
      { date: "2024-11-10", absence: null },
    ],
  },
];

export const allStudents = [
  {
    id: 1,
    name: "Cavid",
    surname: "Quliyev",
    fatherName: "Əli",
    email: "cavid@gmail.com",
    phone: "+994123456781",
    address: "Bakı şəhəri",
    image: null,
    joinDate: "01-09-2021",
    point: 573,
    university: "Bakı Dövlət Universiteti",
    faculty: "İqtisadiyyat",
    admissionDate: "01-09-2021",
  },
  {
    id: 2,
    name: "Nərmin",
    surname: "Əliyeva",
    fatherName: "Anar",
    email: "nermin@gmail.com",
    phone: "+994123456782",
    address: "Gəncə şəhəri",
    image: null,
    joinDate: "10-09-2021",
    point: 612,
    university: "Azərbaycan Tibb Universiteti",
    faculty: "Tibb",
    admissionDate: "10-09-2021",
  },
  {
    id: 3,
    name: "Elnur",
    surname: "Hüseynov",
    fatherName: "Rasim",
    email: "elnur@gmail.com",
    phone: "+994123456783",
    address: "Sumqayıt şəhəri",
    image: null,
    joinDate: "15-10-2021",
    point: 589,
    university: "ADA Universiteti",
    faculty: "İnformasiya Texnologiyaları",
    admissionDate: "15-10-2021",
  },
  {
    id: 4,
    name: "Gülşən",
    surname: "Məmmədova",
    fatherName: "Elçin",
    email: "gulshe@gmail.com",
    phone: "+994123456784",
    address: "Şəki şəhəri",
    image: null,
    joinDate: "05-11-2021",
    point: 554,
    university: "Azərbaycan Texniki Universiteti",
    faculty: "Kompüter Mühəndisliyi",
    admissionDate: "05-11-2021",
  },
  {
    id: 5,
    name: "Vüqar",
    surname: "Əhmədov",
    fatherName: "Cəmil",
    email: "vuqar@gmail.com",
    phone: "+994123456785",
    address: "Mingəçevir şəhəri",
    image: null,
    joinDate: "18-11-2021",
    point: 521,
    university: "Azərbaycan Dillər Universiteti",
    faculty: "Xarici Dillər",
    admissionDate: "18-11-2021",
  },
  {
    id: 6,
    name: "Aysel",
    surname: "Qasımova",
    fatherName: "Samir",
    email: "aysel@gmail.com",
    phone: "+994123456786",
    address: "Lənkəran şəhəri",
    image: null,
    joinDate: "23-11-2021",
    point: 640,
    university: "Azərbaycan Dövlət İqtisad Universiteti",
    faculty: "Maliyyə",
    admissionDate: "23-11-2021",
  },
  {
    id: 7,
    name: "Elşən",
    surname: "İsmayılov",
    fatherName: "Toğrul",
    email: "elshen@gmail.com",
    phone: "+994123456787",
    address: "Bərdə şəhəri",
    image: null,
    joinDate: "30-11-2021",
    point: 558,
    university: "Qafqaz Universiteti",
    faculty: "İnşaat Mühəndisliyi",
    admissionDate: "30-11-2021",
  },
  {
    id: 8,
    name: "Leyla",
    surname: "Qurbanova",
    fatherName: "Əhməd",
    email: "leyla@gmail.com",
    phone: "+994123456788",
    address: "Bakı şəhəri",
    image: null,
    joinDate: "07-12-2021",
    point: 580,
    university: "Naxçıvan Dövlət Universiteti",
    faculty: "Mühasibatlıq",
    admissionDate: "07-12-2021",
  },
  {
    id: 9,
    name: "Nihad",
    surname: "Rzayev",
    fatherName: "Arif",
    email: "nihad@gmail.com",
    phone: "+994123456789",
    address: "Şirvan şəhəri",
    image: null,
    joinDate: "12-12-2021",
    point: 630,
    university: "Bakı Ali Neft Məktəbi",
    faculty: "Neft və Qaz Mühəndisliyi",
    admissionDate: "12-12-2021",
  },
  {
    id: 10,
    name: "Ülviyyə",
    surname: "Məmmədova",
    fatherName: "Elxan",
    email: "ulviyye@gmail.com",
    phone: "+994123456780",
    address: "Quba şəhəri",
    image: null,
    joinDate: "19-12-2021",
    point: 607,
    university: "Azərbaycan Dövlət Pedaqoji Universiteti",
    faculty: "Təbiət Elmləri",
    admissionDate: "19-12-2021",
  },
  {
    id: 11,
    name: "Fərid",
    surname: "Əliyev",
    fatherName: "Zaur",
    email: "ferid@gmail.com",
    phone: "+994123456781",
    address: "Xırdalan şəhəri",
    image: null,
    joinDate: "25-12-2021",
    point: 590,
    university: "ADA Universiteti",
    faculty: "Siyasi Elmlər",
    admissionDate: "25-12-2021",
  },
  {
    id: 12,
    name: "Şəfa",
    surname: "İsmayılova",
    fatherName: "Mehman",
    email: "shefa@gmail.com",
    phone: "+994123456782",
    address: "Sumqayıt şəhəri",
    image: null,
    joinDate: "02-01-2022",
    point: 615,
    university: "Azərbaycan Dövlət Rəssamlıq Akademiyası",
    faculty: "İncəsənət",
    admissionDate: "02-01-2022",
  },
  {
    id: 13,
    name: "Elçin",
    surname: "Mehdiyev",
    fatherName: "Rəşad",
    email: "elchin@gmail.com",
    phone: "+994123456783",
    address: "Gəncə şəhəri",
    image: null,
    joinDate: "10-01-2022",
    point: 570,
    university: "Bakı Dövlət Universiteti",
    faculty: "Riyaziyyat",
    admissionDate: "10-01-2022",
  },
  {
    id: 14,
    name: "Gülnar",
    surname: "Rzayeva",
    fatherName: "Səlim",
    email: "gulnar@gmail.com",
    phone: "+994123456784",
    address: "Şamaxı şəhəri",
    image: null,
    joinDate: "18-01-2022",
    point: 582,
    university: "Azərbaycan Tibb Universiteti",
    faculty: "Aptekçilik",
    admissionDate: "18-01-2022",
  },
  {
    id: 15,
    name: "Orxan",
    surname: "Hüseynov",
    fatherName: "Nəbi",
    email: "orxan@gmail.com",
    phone: "+994123456785",
    address: "Qusar şəhəri",
    image: null,
    joinDate: "25-01-2022",
    point: 620,
    university: "Azərbaycan Dövlət İqtisad Universiteti",
    faculty: "Biznesin İdarə Edilməsi",
    admissionDate: "25-01-2022",
  },
  {
    id: 16,
    name: "Aytən",
    surname: "Əliyeva",
    fatherName: "Rəşid",
    email: "ayten@gmail.com",
    phone: "+994123456786",
    address: "Mingəçevir şəhəri",
    image: null,
    joinDate: "01-02-2022",
    point: 553,
    university: "Azərbaycan Dövlət Neft və Sənaye Universiteti",
    faculty: "İnformasiya Texnologiyaları",
    admissionDate: "01-02-2022",
  },
  {
    id: 17,
    name: "Fidan",
    surname: "Mustafayeva",
    fatherName: "Arzu",
    email: "fidan@gmail.com",
    phone: "+994123456787",
    address: "Bakı şəhəri",
    image: null,
    joinDate: "08-02-2022",
    point: 610,
    university: "ADA Universiteti",
    faculty: "Dizayn",
    admissionDate: "08-02-2022",
  },
  {
    id: 18,
    name: "İlqar",
    surname: "Məmmədov",
    fatherName: "Səfər",
    email: "ilqar@gmail.com",
    phone: "+994123456788",
    address: "Sumqayıt şəhəri",
    image: null,
    joinDate: "15-02-2022",
    point: 596,
    university: "Bakı Ali Neft Məktəbi",
    faculty: "Mexanika Mühəndisliyi",
  },
  {
    id: 19,
    name: "Əfsanə",
    surname: "Əliyeva",
    fatherName: "Bəhram",
    email: "efsane@gmail.com",
    phone: "+994123456789",
    address: "Gəncə şəhəri",
    image: null,
    joinDate: "22-02-2022",
    point: 605,
    university: "Bakı Dövlət Universiteti",
    faculty: "Psixologiya",
  },
  {
    id: 20,
    name: "Rəna",
    surname: "Quliyeva",
    fatherName: "Adil",
    email: "rena@gmail.com",
    phone: "+994123456790",
    address: "Bərdə şəhəri",
    image: null,
    joinDate: "01-03-2022",
    point: 578,
    university: "Azərbaycan Dövlət İqtisad Universiteti",
    faculty: "Statistika",
  },
  {
    id: 21,
    name: "Elçin",
    surname: "Qasımov",
    fatherName: "Ələsgər",
    email: "elchin@gmail.com",
    phone: "+994123456791",
    address: "Xırdalan şəhəri",
    image: null,
    joinDate: "09-03-2022",
    point: 600,
    university: "Azərbaycan Dövlət İqtisad Universiteti",
    faculty: "Maliyyə",
  },
  {
    id: 22,
    name: "Səidə",
    surname: "Abdullayeva",
    fatherName: "Vaqif",
    email: "saida@gmail.com",
    phone: "+994123456792",
    address: "Şəki şəhəri",
    image: null,
    joinDate: "17-03-2022",
    point: 585,
    university: "Bakı Dövlət Universiteti",
    faculty: "Filologiya",
  },
  {
    id: 23,
    name: "Kənan",
    surname: "Rzayev",
    fatherName: "Cəmil",
    email: "kenan@gmail.com",
    phone: "+994123456793",
    address: "Şamaxı şəhəri",
    image: null,
    joinDate: "25-03-2022",
    point: 612,
    university: "ADA Universiteti",
    faculty: "Beynəlxalq Münasibətlər",
  },
  {
    id: 24,
    name: "İlahə",
    surname: "Əhmədova",
    fatherName: "Əhməd",
    email: "ilahe@gmail.com",
    phone: "+994123456794",
    address: "Lənkəran şəhəri",
    image: null,
    joinDate: "03-04-2022",
    point: 630,
    university: "Azərbaycan Texniki Universiteti",
    faculty: "Elektronika",
  },
  {
    id: 25,
    name: "Murad",
    surname: "Mustafayev",
    fatherName: "Fikrət",
    email: "murad@gmail.com",
    phone: "+994123456795",
    address: "Quba şəhəri",
    image: null,
    joinDate: "11-04-2022",
    point: 577,
    university: "Azərbaycan Dövlət İqtisad Universiteti",
    faculty: "İqtisadiyyat",
  },
];



export const teachers = [
  {
    id: 1,
    name: "Ali",
    surname: "Doe",
    fatherName: "Huseyn",
    email: "ali.doe@example.com",
    phone: "+1234567890",
    address: "1234 North Street, New York",
    image: null,
    filialID: 1,
    joinDate: "2021-12-12",
  },
  {
    id: 2,
    name: "Mehmet",
    surname: "Kaya",
    fatherName: "Mustafa",
    email: "mehmet.kaya@example.com",
    phone: "+1234567891",
    address: "5678 South Avenue, Los Angeles",
    image: null,
    filialID: 2,
    joinDate: "2020-05-20",
  },
  {
    id: 3,
    name: "Ayşe",
    surname: "Demir",
    fatherName: "Ahmet",
    email: "ayse.demir@example.com",
    phone: "+1234567892",
    address: "9101 West Lane, Chicago",
    image: null,
    filialID: 1,
    joinDate: "2019-03-15",
  },
  {
    id: 4,
    name: "John",
    surname: "Smith",
    fatherName: "Edward",
    email: "john.smith@example.com",
    phone: "+1234567893",
    address: "1112 East Boulevard, Miami",
    image: null,
    filialID: 3,
    joinDate: "2018-08-10",
  },
  {
    id: 5,
    name: "Elif",
    surname: "Yılmaz",
    fatherName: "Ali",
    email: "elif.yilmaz@example.com",
    phone: "+1234567894",
    address: "1314 South Road, Seattle",
    image: null,
    filialID: 2,
    joinDate: "2020-11-18",
  },
  {
    id: 6,
    name: "Fatma",
    surname: "Öztürk",
    fatherName: "Kemal",
    email: "fatma.ozturk@example.com",
    phone: "+1234567895",
    address: "1516 North Street, San Francisco",
    image: null,
    filialID: 1,
    joinDate: "2022-02-28",
  },
  {
    id: 7,
    name: "David",
    surname: "Brown",
    fatherName: "Michael",
    email: "david.brown@example.com",
    phone: "+1234567896",
    address: "1718 West Avenue, Boston",
    image: null,
    filialID: 3,
    joinDate: "2017-07-23",
  },
  {
    id: 8,
    name: "Sibel",
    surname: "Kara",
    fatherName: "Hasan",
    email: "sibel.kara@example.com",
    phone: "+1234567897",
    address: "1920 South Boulevard, Washington",
    image: null,
    filialID: 2,
    joinDate: "2020-09-30",
  },
  {
    id: 9,
    name: "Lucas",
    surname: "Davis",
    fatherName: "Robert",
    email: "lucas.davis@example.com",
    phone: "+1234567898",
    address: "2122 North Road, Dallas",
    image: null,
    filialID: 1,
    joinDate: "2016-10-22",
  },
  {
    id: 10,
    name: "Emma",
    surname: "Green",
    fatherName: "William",
    email: "emma.green@example.com",
    phone: "+1234567899",
    address: "2324 West Street, Houston",
    image: null,
    filialID: 3,
    joinDate: "2021-01-01",
  },
  {
    id: 11,
    name: "Nihat",
    surname: "Erkan",
    fatherName: "Salih",
    email: "nihat.erkan@example.com",
    phone: "+1234567810",
    address: "2526 East Avenue, Austin",
    image: null,
    filialID: 2,
    joinDate: "2019-06-19",
  },
  {
    id: 12,
    name: "Ayhan",
    surname: "Çetin",
    fatherName: "Veli",
    email: "ayhan.cetin@example.com",
    phone: "+1234567811",
    address: "2728 North Lane, Denver",
    image: null,
    filialID: 1,
    joinDate: "2018-12-05",
  },
  {
    id: 13,
    name: "Canan",
    surname: "Güneş",
    fatherName: "Murat",
    email: "canan.gunes@example.com",
    phone: "+1234567812",
    address: "2930 West Road, Phoenix",
    image: null,
    filialID: 3,
    joinDate: "2017-04-07",
  },
  {
    id: 14,
    name: "Selim",
    surname: "Kurt",
    fatherName: "Zafer",
    email: "selim.kurt@example.com",
    phone: "+1234567813",
    address: "3132 South Street, Las Vegas",
    image: null,
    filialID: 2,
    joinDate: "2020-07-21",
  },
  {
    id: 15,
    name: "Leyla",
    surname: "Aksoy",
    fatherName: "Ahmet",
    email: "leyla.aksoy@example.com",
    phone: "+1234567814",
    address: "3334 North Avenue, San Diego",
    image: null,
    filialID: 1,
    joinDate: "2019-10-13",
  },
  {
    id: 16,
    name: "Alex",
    surname: "Johnson",
    fatherName: "George",
    email: "alex.johnson@example.com",
    phone: "+1234567815",
    address: "3536 West Lane, San Jose",
    image: null,
    filialID: 3,
    joinDate: "2021-05-08",
  },
  {
    id: 17,
    name: "Gül",
    surname: "Çelik",
    fatherName: "İbrahim",
    email: "gul.celik@example.com",
    phone: "+1234567816",
    address: "3738 South Boulevard, Charlotte",
    image: null,
    filialID: 2,
    joinDate: "2022-03-19",
  },
  {
    id: 18,
    name: "Jasper",
    surname: "Williams",
    fatherName: "Henry",
    email: "jasper.williams@example.com",
    phone: "+1234567817",
    address: "3940 East Road, Detroit",
    image: null,
    filialID: 1,
    joinDate: "2020-08-03",
  },
  {
    id: 19,
    name: "Zeynep",
    surname: "Şahin",
    fatherName: "Emir",
    email: "zeynep.sahin@example.com",
    phone: "+1234567818",
    address: "4142 North Avenue, Portland",
    image: null,
    filialID: 3,
    joinDate: "2021-10-22",
  },
  {
    id: 20,
    name: "Hakan",
    surname: "Gök",
    fatherName: "Ali",
    email: "hakan.gok@example.com",
    phone: "+1234567819",
    address: "4344 South Street, Atlanta",
    image: null,
    filialID: 2,
    joinDate: "2019-02-11",
  },
];


export const mycourses = [
  {
    id: 1,
    name:"Riyaziyyat",
    teacher:"Ali Huseynov",
    time:"10:00",
    
    dates:[
      "2024-11-01",
      "2024-11-03",
      "2024-11-05",
      "2024-11-08",
      "2024-11-10",
      "2024-11-12",
      "2024-11-15",
      "2024-11-17",
    ],


  },
  {
    id: 2,
    name:"Fizika",
    teacher:"Mehmet Kaya",
    time:"12:00",
    dates:[
      "2024-11-02",
      "2024-11-03",
      "2024-11-04",
      "2024-11-06",
      "2024-11-09",
      "2024-11-11",
      "2024-11-13",
      "2024-11-16",
      "2024-11-18",
    ],
  },
  {
    id: 3,
    name:"Kimya",
    teacher:"Ayşe Demir",
    time:"14:00",
    dates:[
      "2024-11-01",
      "2024-11-03",
      "2024-11-05",
      "2024-11-08",
      "2024-11-10",
      "2024-11-12",
      "2024-11-15",
      "2024-11-17",
    ],
  }

]




export const posts = [
  {
    id: 1,
    title: "Lorem ipsum dolor sit amet",
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel odio et felis vulputate tincidunt. Nulla ac venenatis nunc. Ut vehicula leo sit amet lectus feugiat, eu volutpat turpis dignissim. Nam tempor nulla ac lorem pharetra, ut sollicitudin nulla vehicula. Sed tempor libero et felis convallis, vel lacinia urna vehicula. Vestibulum eget interdum magna, id cursus felis. Aliquam erat volutpat. Nulla nec lorem ut metus malesuada varius. Aenean nec dui in nunc convallis auctor. In hac habitasse platea dictumst. Curabitur id urna quis nunc efficitur tempor vel ac erat. Suspendisse potenti. Integer lobortis orci eu dolor volutpat, ac interdum nisi feugiat. Mauris pharetra orci nec dui tincidunt, a hendrerit lorem fermentum. Sed lobortis venenatis justo, id dapibus purus ullamcorper id. Integer quis posuere felis. Ut auctor est sed turpis ultricies dictum. Nunc fermentum maximus nunc. Quisque convallis ligula vel arcu placerat, a convallis ex ullamcorper. Donec hendrerit malesuada metus ut elementum.",
    author: "Ali Huseynov",
    date: "2024-11-01",
  },
  {
    id: 2,
    title: "Aliquam vestibulum purus sed orci egestas,",
    content: "Aliquam vestibulum purus sed orci egestas, sed fermentum justo faucibus. Nulla id tristique justo. Nam hendrerit orci sit amet gravida dapibus. Curabitur sagittis ipsum a ultricies tincidunt. Cras fringilla, elit nec volutpat sollicitudin, libero ante rutrum libero, sed laoreet elit odio ut nulla. Mauris consequat dui vel velit placerat, non dictum orci bibendum. Integer congue risus vel sollicitudin laoreet. Phasellus gravida auctor ligula, ac lacinia purus faucibus in. Ut consequat risus quis lectus sodales, sed sollicitudin lorem tincidunt. Aenean sit amet erat volutpat, volutpat urna at, hendrerit ipsum. Duis nec ipsum at nisi sodales suscipit. Aliquam erat volutpat. Sed faucibus libero et vestibulum viverra. Fusce consectetur mollis erat, a efficitur urna maximus nec. Cras tempor erat id nunc cursus, at lobortis tortor fermentum. Nunc eget libero vel odio sollicitudin faucibus ac ac elit. Pellentesque sollicitudin, turpis eu vehicula feugiat, purus sapien feugiat lorem, non ultricies eros nulla eget nisi.",
    author: "Ali Huseynov",
    date: "2024-11-02",
  },
  {
    id: 3,
    title: "Fusce et magna libero. Aenean tempor suscipit dui in lacinia. Vivamus condimentum auctor gravida",
    content: "Fusce et magna libero. Aenean tempor suscipit dui in lacinia. Vivamus condimentum auctor gravida. Nunc ac ante nec nisl malesuada convallis. Sed auctor convallis orci in tempus. Integer maximus leo vel neque volutpat, sed maximus elit pretium. Curabitur interdum turpis libero, vel volutpat velit auctor sit amet. Proin lobortis odio at sapien vehicula placerat. Nulla sit amet nulla lorem. In maximus sem ac sollicitudin vestibulum. Aenean viverra ex vel lacus hendrerit, vel facilisis ante vehicula. Nunc malesuada orci sed felis cursus, et auctor magna placerat. Nam tincidunt velit id elit malesuada mollis. Nam imperdiet, sapien non facilisis fermentum, eros augue tincidunt ligula, in pharetra purus metus ac lorem. Sed pharetra suscipit sapien vel hendrerit. Etiam convallis ultricies nulla, vitae auctor nunc. Donec pretium suscipit turpis, sit amet viverra neque suscipit vel. Sed rhoncus ipsum ut ante vehicula, eget laoreet nisi pellentesque. Pellentesque consequat vitae orci id viverra. Etiam venenatis orci ut neque ultricies, eu egestas nisl aliquet.",
    author: "Ali Huseynov",
    date: "2024-11-03",
  },
  {
    id: 4,
    title: "Mauris sagittis, ligula eget vestibulum faucibus, ",
    content: "Mauris sagittis, ligula eget vestibulum faucibus, orci ante eleifend enim, eget aliquam orci felis a purus. Integer egestas, erat vitae tempor dignissim, purus velit egestas lectus, ut consequat enim lorem et eros. Nam mollis ipsum ligula, a luctus urna suscipit id. Sed accumsan magna ipsum, eget bibendum risus gravida id. Etiam congue risus ipsum, non ullamcorper odio mollis in. Integer ut tortor nec eros sodales maximus et ac ante. Phasellus vehicula lobortis nisi, eu placerat enim viverra id. Pellentesque vestibulum massa in dui sollicitudin suscipit. In lobortis magna eget eros scelerisque, sit amet tristique ipsum maximus. Aenean rhoncus, magna at gravida rhoncus, ante sem accumsan enim, id maximus nisi augue at augue. Aliquam ultricies volutpat lorem id condimentum. Cras euismod eros eget lectus convallis tempus. Sed in tortor at lectus gravida iaculis vel sit amet enim. Sed malesuada, lorem eget laoreet luctus, elit ipsum tempor risus, eget ullamcorper dui ligula vitae libero. In at justo placerat, varius eros at, cursus justo. Fusce sit amet magna et metus laoreet tempus.",
    author: "Ali Huseynov",
    date: "2024-11-04",
  },
  {
    id: 5,
    title: "Post 5",
    content: "Cras tristique tincidunt urna in lacinia. Nam ac lectus et ligula congue consectetur ut at erat. Donec luctus sollicitudin sem sit amet tincidunt. Integer et auctor erat. Mauris finibus, nulla nec viverra vehicula, eros libero fringilla magna, sit amet dignissim turpis arcu a arcu. Ut vel ligula sit amet elit volutpat lacinia. Sed pharetra tortor a mauris condimentum mollis. In auctor ut nisl id tincidunt. Etiam eleifend justo nec ligula vulputate lobortis. Nam sagittis, arcu non tincidunt varius, orci ante suscipit ligula, ac malesuada lorem ante non nulla. Sed eleifend turpis vel ligula auctor, at sollicitudin turpis facilisis. Proin elementum urna nec tortor convallis ullamcorper. In dictum lorem vel turpis gravida lobortis. Curabitur vel nulla ac eros fermentum tristique sit amet vitae est. Nam maximus ipsum ac nulla pellentesque, ac dapibus turpis eleifend. Suspendisse quis nulla vel eros eleifend tempus.",
    author: "Ali Huseynov",
    date: "2024-11-05",
  },
  {
    id: 6,
    title: "Sed tristique elit et lectus feugiat,",
    content: "Sed tristique elit et lectus feugiat, et pretium nunc iaculis. Cras egestas quam sit amet orci condimentum, non condimentum lectus sollicitudin. Donec mollis ipsum velit, ut cursus sapien volutpat eget. Nam mollis nibh eu velit consequat cursus. Integer sit amet fringilla ante, at tincidunt velit. Etiam sagittis tempor dui. Curabitur in varius elit. Integer nec laoreet risus. Suspendisse ut quam dolor. Donec at tristique nisi. Integer euismod ac augue vitae volutpat. Etiam pharetra, mi id tincidunt viverra, mauris lorem posuere risus, ac dictum lacus ante eu leo. Sed dapibus bibendum magna a rutrum. Nulla viverra sem nec elit faucibus, sed auctor tortor lacinia. Ut non est sem. Nam auctor convallis turpis at efficitur.",
    author: "Ali Huseynov",
    date: "2024-11-06",
  },
  {
    id: 7,
    title: "Post 7",
    content: "Cras ut libero scelerisque, convallis nisi at, feugiat magna. Donec bibendum tortor ac purus placerat, eu convallis lectus facilisis. Etiam bibendum, nisl ac auctor suscipit, lacus nisl rutrum nulla, ut efficitur metus felis id felis. Suspendisse potenti. Nam ac velit sit amet felis sodales tempus non non est. Fusce at leo mauris. Nulla facilisi. Ut tincidunt ipsum et metus auctor lobortis. Integer vulputate et nunc nec viverra. Nam sit amet nulla libero. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer at erat in lacus sollicitudin aliquet ac eu urna. In mollis nisi a est vehicula pretium. Nunc sit amet consequat augue, a fringilla libero. Ut tincidunt convallis nibh, id vehicula justo porttitor non. Morbi ultricies posuere enim, eget tristique eros maximus non.",
    author: "Ali Huseynov",
    date: "2024-11-07",
  },
  {
    id: 8,
    title: "Post 8",
    content: "Pellentesque tempor posuere sem at facilisis. Fusce vel risus vitae sapien posuere efficitur. Etiam aliquam volutpat augue, id convallis erat finibus et. Vestibulum viverra libero ut mi dignissim, non ullamcorper purus eleifend. Mauris pellentesque, felis sit amet interdum maximus, ipsum orci varius elit, eget volutpat lorem libero id lectus. Ut ut elit sit amet urna gravida varius a sit amet est. Integer at quam erat. Suspendisse condimentum sapien in erat tincidunt, ut faucibus mauris egestas. Nam malesuada sapien ut magna hendrerit, sed dapibus ipsum malesuada. Curabitur nec gravida est. Curabitur vitae libero nec libero sodales pellentesque. In facilisis, dui non cursus volutpat, sapien orci feugiat augue, a sagittis metus turpis sit amet felis.",
    author: "Ali Huseynov",
    date: "2024-11-08",
  },
  {
    id: 9,
    title: "Post 9",
    content: "Nullam varius libero in nunc ullamcorper ultricies. Nulla hendrerit lectus id metus consectetur, nec pharetra ligula tristique. Phasellus eu magna in purus ullamcorper dictum ut vel erat. Sed id lorem mi. Cras feugiat mollis nulla, vitae feugiat metus cursus sit amet. Mauris varius, elit et rutrum efficitur, lectus nisl fermentum lectus, ut pretium magna nisi at erat. Sed ut neque in nulla lobortis feugiat eget et libero. Vivamus consequat venenatis magna, sit amet fermentum risus egestas sit amet. Nulla ullamcorper, libero in varius auctor, sapien tortor cursus velit, nec auctor mi purus eget est. Nunc a felis id eros convallis condimentum. Etiam vulputate auctor ipsum, ac sollicitudin lorem tincidunt et.",
    author: "Ali Huseynov",
    date: "2024-11-09",
  },
  {
    id: 10,
    title: "Post 10",
    content: "Aliquam sit amet nisi vel dolor faucibus varius. Suspendisse ac sapien a felis feugiat tincidunt sit amet sit amet ligula. Cras gravida ligula at est vehicula, ac varius lorem aliquam. Nunc congue orci non mi sodales tristique. Proin id mi ac ligula vehicula sollicitudin non non ante. In et nunc vel libero condimentum tincidunt non at dui. Integer mollis risus sapien, a sollicitudin orci facilisis et. Sed posuere risus et neque placerat, in tristique turpis tincidunt. Nam vulputate tortor eu felis dignissim lacinia. Integer ac lorem et turpis convallis efficitur a a velit. Nunc eget mollis turpis, vel suscipit nisi. Vestibulum ut justo id orci maximus malesuada non id lorem. Ut vestibulum felis at felis pharetra volutpat.",
    author: "Ali Huseynov",
    date: "2024-11-10",
  },
  {
    id: 11,
    title: "Post 11",
    content: "Nulla facilisi. Nam feugiat, dui ac efficitur venenatis, libero magna fermentum neque, eget cursus velit leo sit amet justo. Cras ac ante auctor, consectetur ante et, pellentesque sapien. Nunc dictum risus vitae orci venenatis, ut rhoncus ligula cursus. Sed et felis et purus cursus ultricies sit amet eget libero. In euismod orci ac velit malesuada suscipit. Cras sollicitudin erat eget metus vehicula, vel hendrerit odio interdum. Sed orci libero, congue et sagittis vitae, viverra vel urna. Fusce volutpat pharetra mi. Aenean mollis et justo at consequat. Donec et pharetra odio. Quisque porttitor tristique lorem, vel malesuada metus interdum vitae.",
    author: "Ali Huseynov",
    date: "2024-11-11",
  },
  {
    id: 12,
    title: "Post 12",
    content: "Mauris in odio leo. Etiam fringilla turpis a nulla posuere, vel euismod ipsum viverra. Ut ornare sem sed libero tincidunt, id lacinia turpis tempus. Donec hendrerit purus et consectetur malesuada. Aliquam erat volutpat. Curabitur ac nulla in nisi placerat porttitor et eget libero. Fusce ut nisl id lorem maximus malesuada. Donec tempus, nulla eget tincidunt auctor, lorem purus consequat lectus, ac tristique risus nisl sit amet metus. Nam volutpat orci libero, sit amet tincidunt ligula cursus vitae. Integer molestie libero vel libero rutrum auctor. Aenean sollicitudin maximus orci, eu lacinia odio tempor et. Sed et nisi eget metus tristique elementum in id enim.",
    author: "Ali Huseynov",
    date: "2024-11-12",
  },
  {
    id: 13,
    title: "Post 13",
    content: "Pellentesque posuere quam sed felis malesuada, id euismod nunc posuere. Curabitur a ullamcorper sapien. Donec fermentum sapien leo, sed tristique dui aliquet et. Nam ac lectus justo. Cras posuere turpis orci, id placerat purus maximus at. Integer sodales lectus eget dui sollicitudin, nec congue sem lobortis. Nam sed dui vel elit efficitur rhoncus id sit amet eros. Sed eget varius magna. Donec nec odio sem. Pellentesque et libero non eros pharetra lobortis.",
    author: "Ali Huseynov",
    date: "2024-11-13",
  },
  {
    id: 14,
    title: "Post 14",
    content: "In tristique sem at libero fermentum sollicitudin. Mauris vehicula id felis eget porttitor. Quisque malesuada ut sem in dictum. Ut consequat, lorem sed bibendum fermentum, ligula justo malesuada ligula, ut tristique turpis turpis eu libero. Nulla ac vestibulum enim. Morbi aliquam augue nec orci pharetra, in viverra sem accumsan. Nulla tempor eros sit amet posuere vulputate. Ut felis tortor, fermentum vitae purus vel, dapibus varius orci. Nam viverra orci quam, vel vehicula ligula accumsan eget. Sed et ex sit amet turpis feugiat condimentum. Donec vehicula volutpat ex, sit amet sollicitudin magna suscipit sed.",
    author: "Ali Huseynov",
    date: "2024-11-14",
  },
  {
    id: 15,
    title: "Post 15",
    content: "Sed ut eros id quam rutrum vehicula. Nulla ornare felis in diam feugiat laoreet. Donec ac vehicula felis. Cras id elit egestas, elementum velit ut, auctor dolor. Proin dignissim felis et sapien laoreet, eget dictum lorem malesuada. Nam volutpat tincidunt risus at feugiat. Etiam sed sapien tincidunt, tincidunt lorem vel, molestie ligula. Fusce tempor pharetra libero, ac pharetra mauris lacinia ac. Curabitur in bibendum odio. Donec non mauris in nulla volutpat egestas. In vitae enim mauris. Ut ullamcorper lorem leo, ac tincidunt metus fringilla vitae. Nam malesuada felis in ante maximus, id volutpat odio tristique.",
    author: "Ali Huseynov",
    date: "2024-11-15",
  },
];
